/** Models the installed pi-ai catalog has not shipped yet; see catalog-supplement.ts. */
import type { Api, Model } from '@earendil-works/pi-ai'

export const CATALOG_SUPPLEMENT: Readonly<Record<string, Readonly<Record<string, Model<Api>>>>> = {
  'openai-codex': {
    'gpt-6-luna': {
      'id': 'gpt-6-luna',
      'name': 'GPT-6 Luna',
      'api': 'openai-codex-responses',
      'provider': 'openai-codex',
      'baseUrl': 'https://chatgpt.com/backend-api',
      'reasoning': true,
      'input': [
        'text',
        'image',
      ],
      'cost': {
        'input': 0.1,
        'output': 0.5,
        'cacheRead': 0.01,
        'cacheWrite': 0.125,
        'tiers': [
          {
            'inputTokensAbove': 272000,
            'input': 0.2,
            'output': 0.75,
            'cacheRead': 0.02,
            'cacheWrite': 0.25,
          },
        ],
      },
      'contextWindow': 1050000,
      'maxTokens': 128000,
      'thinkingLevelMap': {
        'xhigh': 'xhigh',
        'max': 'max',
        'minimal': 'low',
      },
      'compat': {
        'supportsOpenAIGrammarTools': true,
        'supportsAdditionalTools': true,
        'supportsToolSearch': true,
      },
    },
    'gpt-6-sol': {
      'id': 'gpt-6-sol',
      'name': 'GPT-6 Sol',
      'api': 'openai-codex-responses',
      'provider': 'openai-codex',
      'baseUrl': 'https://chatgpt.com/backend-api',
      'reasoning': true,
      'input': [
        'text',
        'image',
      ],
      'cost': {
        'input': 2,
        'output': 10,
        'cacheRead': 0.2,
        'cacheWrite': 2.5,
        'tiers': [
          {
            'inputTokensAbove': 272000,
            'input': 4,
            'output': 15,
            'cacheRead': 0.4,
            'cacheWrite': 5,
          },
        ],
      },
      'contextWindow': 1050000,
      'maxTokens': 128000,
      'thinkingLevelMap': {
        'xhigh': 'xhigh',
        'max': 'max',
        'minimal': 'low',
      },
      'compat': {
        'supportsOpenAIGrammarTools': true,
        'supportsAdditionalTools': true,
        'supportsToolSearch': true,
      },
    },
  },
  'openai': {
    'gpt-6-luna': {
      'id': 'gpt-6-luna',
      'name': 'GPT-6 Luna',
      'api': 'openai-responses',
      'provider': 'openai',
      'baseUrl': 'https://api.openai.com/v1',
      'reasoning': true,
      'input': [
        'text',
        'image',
      ],
      'cost': {
        'input': 0.1,
        'output': 0.5,
        'cacheRead': 0.01,
        'cacheWrite': 0.125,
        'tiers': [
          {
            'inputTokensAbove': 272000,
            'input': 0.2,
            'output': 0.75,
            'cacheRead': 0.02,
            'cacheWrite': 0.25,
          },
        ],
      },
      'contextWindow': 1050000,
      'maxTokens': 128000,
      'thinkingLevelMap': {
        'off': null,
        'minimal': null,
        'low': 'low',
        'medium': 'medium',
        'high': 'high',
        'xhigh': 'xhigh',
        'max': 'max',
      },
      'compat': {
        'supportsStrictMode': true,
        'supportsOpenAIGrammarTools': true,
        'supportsAdditionalTools': true,
        'supportsToolSearch': true,
        'supportsExplicitPromptCacheMode': true,
      },
    },
    'gpt-6-sol': {
      'id': 'gpt-6-sol',
      'name': 'GPT-6 Sol',
      'api': 'openai-responses',
      'provider': 'openai',
      'baseUrl': 'https://api.openai.com/v1',
      'reasoning': true,
      'input': [
        'text',
        'image',
      ],
      'cost': {
        'input': 2,
        'output': 10,
        'cacheRead': 0.2,
        'cacheWrite': 2.5,
        'tiers': [
          {
            'inputTokensAbove': 272000,
            'input': 4,
            'output': 15,
            'cacheRead': 0.4,
            'cacheWrite': 5,
          },
        ],
      },
      'contextWindow': 1050000,
      'maxTokens': 128000,
      'thinkingLevelMap': {
        'off': null,
        'minimal': null,
        'low': 'low',
        'medium': 'medium',
        'high': 'high',
        'xhigh': 'xhigh',
        'max': 'max',
      },
      'compat': {
        'supportsStrictMode': true,
        'supportsOpenAIGrammarTools': true,
        'supportsAdditionalTools': true,
        'supportsToolSearch': true,
        'supportsExplicitPromptCacheMode': true,
      },
    },
  },
  'anthropic': {
    'claude-opus-5-5': {
      'id': 'claude-opus-5-5',
      'name': 'Claude Opus 5.5',
      'api': 'anthropic-messages',
      'provider': 'anthropic',
      'baseUrl': 'https://api.anthropic.com',
      'reasoning': true,
      'input': [
        'text',
        'image',
      ],
      'cost': {
        'input': 4,
        'output': 20,
        'cacheRead': 0.2,
        'cacheWrite': 5,
      },
      'contextWindow': 1000000,
      'maxTokens': 128000,
      'compat': {
        'supportsMidConvoEffort': true,
        'forceAdaptiveThinking': true,
        'supportsTemperature': false,
        'supportsStrictTools': true,
      },
      'thinkingLevelMap': {
        'off': null,
        'xhigh': 'xhigh',
        'max': 'max',
      },
    },
  },
} as const satisfies Readonly<Record<string, Readonly<Record<string, Model<Api>>>>>
